### ISSUE TITLE
Rating component selected state styling 

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-webcomponents#339]
## Description  

Our users can't style the component since it is not possible to style nested ::parts
```SCSS
// This is not possible
igc-rating::part(fraction) {
    igc-rating::part(symbols-wrapper) {
        color: var-get($theme, 'selected-symbols-color');
    }
}
```

We need a new part `selected` in order to achieve that selection
```SCSS
igc-rating::part(symbols-wrapper selected) {
    color: var-get($theme, 'selected-symbols-color');
}
```

That part needs to be added to the symbols-wrapper container that contains the selected symbols.
```HTML
<div style="width: 0%" part="fraction large">
    <div part="symbols-wrapper selected">...</div>
</div>
<div part="symbols-wrapper">...</div>
```
