### ISSUE TITLE
Rating: Add CSS variable to control the symbol size

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-webcomponents#370]
## Description  
I want to be able to alter the size of the rating symbol via a CSS custom property.

## Expected result  
I should be able to write the following, which should change the size of the symbol used in the rating component:

```css
igc-rating {
   --symbol-size: 48px;
}
```
