### ISSUE TITLE
Textarea does not define an `input` CSS part

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-webcomponents#944]
While the API documentation mentions an `input` CSS part, the component Shadow DOM does not define one.
Thus trying to apply custom styles to the underlying textarea as:
```css
igc-textarea::part(input) {
  background-color: lightblue;
}
```
does not work.
